name: flutter_utils
description: "My custom Flutter utils"
version: 0.0.3
homepage: null

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter: null


