import 'package:flutter/material.dart';

extension BuildContextExtension on BuildContext {
  Size get screenSize => MediaQuery.of(this).size;
  double get screenWidth => MediaQuery.of(this).size.width;
  double get screenHeight => MediaQuery.of(this).size.height;
  EdgeInsets get viewPadding => MediaQuery.of(this).viewPadding;
  EdgeInsets get viewInsets => MediaQuery.of(this).viewInsets;
  bool get isSmallScene => MediaQuery.of(this).size.width <= 340;
  bool get isMediumScene => MediaQuery.of(this).size.width <= 375;

  ThemeData get theme => Theme.of(this);
  ColorScheme get colorScheme => Theme.of(this).colorScheme;

  Color get colorPrimary => colorScheme.primary;
  Color get colorOnPrimary => colorScheme.onPrimary;
  Color get colorPrimaryContainer => colorScheme.primaryContainer;
  Color get colorOnPrimaryContainer => colorScheme.onPrimaryContainer;
  Color get colorPrimaryFixed => colorScheme.primaryFixed;
  Color get colorPrimaryFixedDim => colorScheme.primaryFixedDim;
  Color get colorOnPrimaryFixed => colorScheme.onPrimaryFixed;
  Color get colorOnPrimaryFixedVariant => colorScheme.onPrimaryFixedVariant;
  Color get colorSecondary => colorScheme.secondary;
  Color get colorOnSecondary => colorScheme.onSecondary;
  Color get colorSecondaryContainer => colorScheme.secondaryContainer;
  Color get colorOnSecondaryContainer => colorScheme.onSecondaryContainer;
  Color get colorSecondaryFixed => colorScheme.secondaryFixed;
  Color get colorSecondaryFixedDim => colorScheme.secondaryFixedDim;
  Color get colorOnSecondaryFixed => colorScheme.onSecondaryFixed;
  Color get colorOnSecondaryFixedVariant => colorScheme.onSecondaryFixedVariant;
  Color get colorTertiary => colorScheme.tertiary;
  Color get colorOnTertiary => colorScheme.onTertiary;
  Color get colorTertiaryContainer => colorScheme.tertiaryContainer;
  Color get colorOnTertiaryContainer => colorScheme.onTertiaryContainer;
  Color get colorTertiaryFixed => colorScheme.tertiaryFixed;
  Color get colorTertiaryFixedDim => colorScheme.tertiaryFixedDim;
  Color get colorOnTertiaryFixed => colorScheme.onTertiaryFixed;
  Color get colorOnTertiaryFixedVariant => colorScheme.onTertiaryFixedVariant;
  Color get colorError => colorScheme.error;
  Color get colorOnError => colorScheme.onError;
  Color get colorErrorContainer => colorScheme.errorContainer;
  Color get colorOnErrorContainer => colorScheme.onErrorContainer;
  Color get colorSurface => colorScheme.surface;
  Color get colorOnSurface => colorScheme.onSurface;
  Color get colorSurfaceDim => colorScheme.surfaceDim;
  Color get colorSurfaceBright => colorScheme.surfaceBright;
  Color get colorSurfaceContainerLowest => colorScheme.surfaceContainerLowest;
  Color get colorSurfaceContainerLow => colorScheme.surfaceContainerLow;
  Color get colorSurfaceContainer => colorScheme.surfaceContainer;
  Color get colorSurfaceContainerHigh => colorScheme.surfaceContainerHigh;
  Color get colorSurfaceContainerHighest => colorScheme.surfaceContainerHighest;
  Color get colorOnSurfaceVariant => colorScheme.onSurfaceVariant;
  Color get colorOutline => colorScheme.outline;
  Color get colorOutlineVariant => colorScheme.outlineVariant;
  Color get colorShadow => colorScheme.shadow;
  Color get colorScrim => colorScheme.scrim;
  Color get colorInverseSurface => colorScheme.inverseSurface;
  Color get colorOnInverseSurface => colorScheme.onInverseSurface;
  Color get colorInversePrimary => colorScheme.inversePrimary;
  Color get colorSurfaceTint => colorScheme.surfaceTint;
}
